name: Daily Telegram Reminder

on:
  workflow_dispatch:
  schedule:
    - cron: '55 5 * * *'  # UTC 6:00 = 8:00 Berlin (summer time)
jobs:
  send-telegram:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Message
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHANNEL: '@youforgot'
          MESSAGE: 'You Forgot Something'
        run: |
          curl -s -X POST "https://api.telegram.org/bot${BOT_TOKEN}/sendMessage" \
            -d chat_id="${CHANNEL}" \
            -d text="${MESSAGE}"
